### ISSUE TITLE
connection between the canister and the flutter is not done 

### ISSUE THREAD

**Issue by harshitchugh001** [AstroxNetwork/agent_dart_examples#2]
ERROR: ../../../../.pub-cache/hosted/pub.dev/agent_dart-0.1.19+2/lib/archiver/encoder.dart:99:8: Error: The return type of the method 'SingingBlockZipFileEncoder.addDirectory' is 'void', which does not match the return type, 'Future<void>', of the overridden method, 'ZipFileEncoder.addDirectory'.
ERROR:  - 'Future' is from 'dart:async'.
ERROR: Change to a subtype of 'Future<void>'.
ERROR:   void addDirectory(Directory dir,
ERROR:        ^
ERROR: ../../../../.pub-cache/hosted/pub.dev/archive-3.3.1/lib/src/io/zip_file_encoder.dart:42:16: Context: This is the overridden method ('addDirectory').
ERROR:   Future<void> addDirectory(Directory dir,
ERROR:                ^
ERROR: ../../../../.pub-cache/hosted/pub.dev/agent_dart-0.1.19+2/lib/archiver/encoder.dart:117:8: Error: The return type of the method 'SingingBlockZipFileEncoder.addFile' is 'void', which does not match the return type, 'Future<void>', of the overridden method, 'ZipFileEncoder.addFile'.
ERROR:  - 'Future' is from 'dart:async'.
ERROR: Change to a subtype of 'Future<void>'.
ERROR:   void addFile(File file, [String? filename, int? level = GZIP]) {
ERROR:        ^
ERROR: ../../../../.pub-cache/hosted/pub.dev/archive-3.3.1/lib/src/io/zip_file_encoder.dart:66:16: Context: This is the overridden method ('addFile').

ERROR:   Future<void> addFile(File file, [String? filename, int? level = GZIP]) async {
ERROR:                ^
ERROR: Target kernel_snapshot failed: Exception
Building Linux application...                                           
Exception: Build process failed

![Screenshot from 2023-11-20 09-54-15](https://github.com/AstroxNetwork/agent_dart_examples/assets/123458021/97cbbab8-646a-4075-ba46-22b9a2a1380a)

**Comment by jewel-coredot** [comment]
I have the same issue, how did you solve it?
